version: '3.5'

services:
  mock:
    image: wiremock/wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/logs:/home/wiremock/logs
    command: --global-response-templating
