apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: configmap
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql-root-password
          volumeMounts:
            - mountPath: /servico-cobranca-volume
              name: servico-cobranca-volume
      volumes:
        - name: servico-cobranca-volume
          hostPath:
            path: /home/servico-cobranca-volume
            type: DirectoryOrCreate
