name: Build and Create PR to Develop

on:
  push:
    branches:
      - 'feature**'
      - 'fix**'
      - 'docs**'
      - 'style**'
      - 'refactor**'
      - 'test**'
      - 'chore**'

jobs:
  build:
    uses: ./.github/workflows/reusable-workflow-build.yml

  create_pull_request:
    name: Create Pull Request to Develop
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get feature branch name
        run: echo "FEATURE_BRANCH=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - uses: ./.github/actions/create-pull-request
        with:
          source_branch: $FEATURE_BRANCH
          target_branch: 'develop'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  sonarqube-analysis:
    name: Sonar Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        run: make sonar-analysis SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
