name: Build and Create PR to Develop

on:
  push:
    branches:
      - 'feature**'
      - 'fix**'
      - 'docs**'
      - 'style**'
      - 'refactor**'
      - 'test**'
      - 'chore**'

jobs:
#  build:
#    uses: ./.github/workflows/reusable-workflow-build.yml
#
#  create_pull_request:
#    name: Create Pull Request to Develop
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#      pull-requests: write
#      repository-projects: write
#    needs: build
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Get feature branch name
#        run: echo "FEATURE_BRANCH=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')" >> $GITHUB_ENV
#
#      - uses: ./.github/actions/create-pull-request
#        with:
#          source_branch: $FEATURE_BRANCH
#          target_branch: 'develop'
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#
#  system-tests:
#    name: System Tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Start Wiremock
#        run: make docker-start-wiremock
#
#      - name: Wait for WireMock to be ready
#        run: |
#          until curl -sSf "http://localhost:8081/__admin" >/dev/null; do
#            echo "Waiting for WireMock to be ready..."
#            sleep 15
#          done
#
#      - name: Start App
#        run: |
#          make docker-build
#          make docker-start
#
#      - name: Debug
#        run: |
#          docker compose -f docker-compose-wiremock.yml ps
#          docker compose ps
#
#      - name: Check WireMock Logs
#        run: |
#          docker compose -f docker-compose-wiremock.yml logs
#
#      - name: Wait before running tests
#        run: sleep 20
#
#      - name: Teste
#        run: |
#          RESPONSE=$(curl -sSf http://localhost:8081/__admin)
#          echo "WireMock Response: $RESPONSE"
#
#      - name: Run tests
#        run: make system-test
#
#      - name: Stop Wiremock and App
#        run: |
#          make docker-stop-wiremock
#          make docker-stop

  system-tests:
    name: System Tests
    runs-on: ubuntu-latest
    services:
      mock:
        image: wiremock/wiremock
        ports:
          - "8081:8080"
        volumes:
          - ./wiremock/__files:/home/wiremock/__files
          - ./wiremock/mappings:/home/wiremock/mappings
          - ./wiremock/logs:/home/wiremock/logs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Start Wiremock
#        run: make docker-start-wiremock

      - name: Wait for WireMock to be ready
        run: |
          until curl -sSf "http://localhost:8081/__admin" >/dev/null; do
            echo "Waiting for WireMock to be ready..."
            sleep 10
          done

      - name: Debug
        run: docker ps

      - name: Check WireMock Logs
        run: docker compose -f docker-compose-wiremock.yml logs

      - name: Teste
        run: |
          RESPONSE=$(curl -sSf http://localhost:8081/__admin)
          echo "WireMock Response: $RESPONSE"

#      - name: Stop Wiremock
#        run: make docker-stop-wiremock
